config/routes.rb
# frozen_string_literal: true

# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do
  get '/profile', to: 'users#profile'
  get '/users/new', to: 'users#new'
  get '/users/:id', to: 'users#edit'
  resources :users

  get '/results', to: 'results#index'
  get '/results/:id', to: 'results#run'
  get '/results/:id/spr_coverage', to: 'sprs#coverage_matrix'
  get '/results/:id/req_coverage', to: 'requirements#coverage_matrix'
  get '/results/:id/history', to: 'results#history'
  get '/results/:run/:procedure', to: 'results#procedure'
  get '/execution/:id/:path', to: 'results#procedure_file'

  get '/groups/dependencies/:run', to: 'groups#dependencies'

  get '/procedures', to: 'procedures#index'
  get '/procedures/check_states', to: 'procedures#check_states'
  get '/procedures/:name', to: 'procedures#show'
  get '/procedures/:id/weekly_history', to: 'procedures#weekly_history'
  get '/procedures/:id/total_results', to: 'procedures#total_results'

  get '/about', to: 'static#about'

  get '/tags', to: 'tags#index'
  post '/tags', to: 'tags#create'
  post '/tags/delete', to: 'tags#destroy'
  post '/tags/create_link', to: 'tags#create_link'
  get '/tags/unlink', to: 'tags#unlink'

  get '/sprs', to: 'sprs#index'
  get '/sprs/matrix', to: 'sprs#spr_matrix'
  get '/sprs/:id/edit', to: 'sprs#edit'
  post '/sprs/:id/edit', to: 'sprs#update'
  post '/sprs', to: 'sprs#create'
  post '/sprs/import', to: 'sprs#import'
  get '/sprs/delete', to: 'sprs#destroy'
  get '/sprs/link', to: 'sprs#create_link'
  get '/sprs/unlink', to: 'sprs#unlink'

  get '/requirements', to: 'requirements#index'
  get '/requirements/matrix', to: 'requirements#matrix'
  post '/requirements/import', to: 'requirements#import'
  post '/requirements/import/reqif', to: 'requirements#import_reqif'
  post '/requirements/import/csv', to: 'requirements#import_csv'
  get '/requirements/:id/edit', to: 'requirements#edit'
  post '/requirements/:id/edit', to: 'requirements#update'
  post '/requirements', to: 'requirements#create'
  get '/requirements/delete', to: 'requirements#destroy'
  get '/requirements/link', to: 'requirements#create_link'
  get '/requirements/unlink', to: 'requirements#unlink'

  post '/comments', to: 'comments#create'
  get '/comments/:result_id', to: 'comments#this_execution'
  get '/comments/:result_id/all', to: 'comments#all_executions'

  get '/review-states', to: 'review_states#index'
  post '/review-states', to: 'review_states#create'
  post '/review-states/destroy', to: 'review_states#destroy'

  get '/reviews/:procedure_id', to: 'reviews#index'
  post '/reviews', to: 'reviews#create'

  get '/suggest/:type', to: 'suggestions#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  # Default page to display on root ('/').
  root to: 'static#index'
end
# rubocop:enable Metrics/BlockLength

app/models/user.rb
# frozen_string_literal: true

# User model
# Author johannes.hoelken@hawk.de
class User < ApplicationRecord
  has_many :user_roles, dependent: :destroy
  has_many :roles, through: :user_roles

  has_secure_password

  # Check if the user has the requested role
  # @param roles (Array) the role(s) to check
  def has?(*roles)
    roles.each do |role|
      return true if role_names.include?(role.to_s)
    end
    false
  end

  def role_names
    roles.select(:name).order(name: :asc).map(&:name)
  end

  private

  def symbolic_roles
    %i[admin tester witness user]
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# CRUD Controller for user model
# Author johannes.hoelken@hawk.de
class UsersController < ApplicationController
  before_action :require_admin, except: %i[update profile]
  before_action :set_user, only: %i[edit update destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.order(name: :asc)
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to users_url, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    update_user!
    update_roles!
    redirect_back(fallback_location: edit_user_path(@user), notice: 'User was successfully updated.')
  rescue StandardError => e
    flash[:error] = "Error while editing: #{e.message}"
    render :edit
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def profile
    @user = current_user
    render :edit
  end

  private

  def update_user!
    @user.update!(user_params)
  end

  def update_roles!
    return unless current_user.has?(:admin)

    @user.user_roles.delete_all
    params[:roles].each do |role_id|
      UserRole.create!(user: @user, role: Role.find_by!(id: role_id))
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name, :personal_index, :password, :password_confirmation)
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

# Rails view helper for user specific tasks
#
# Author johannes.hoelken@hawk.de
module UserHelper
  def index_options(user)
    options = [['User Profile', '/profile']]
    options << ['Test Results', '/results'] if user.has?(:tester)
    options << ['Test Procedures', '/procedures'] if user.has?(:tester, :witness)
    options << %w[Requirements /requirements] if user.has?(:tester, :witness)
    options << %w[Users /users] if user.has?(:admin)
    options
  end
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-md-5">
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <div class="input-group-text width-170px">Name</div>
        </div>
        <%= form.text_field :name, class: 'form-control' %>
      </div>
    </div>
  </div>
  <p></p>
  <div class="row">
    <div class="col-md-5">
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <div class="input-group-text width-170px">Personal start</div>
        </div>
        <%= form.select(:personal_index, options_for_select(index_options(user), user.personal_index), {}, {class: 'form-control'}) %>
        <%# form.text_field :personal_index, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-5">
      <small>Configure where you want to start after login.</small>
    </div>
  </div>


  <hr>
  <div class="row">
    <div class="col-md-5">
      <% if current_user.has?(:admin) %>
      <% Role.order(name: :asc).each do |role| %>
        <div class="form-check">
          <input class="form-check-input" type="checkbox"
                 value="<%= role.id %>" id="role-<%= role.id %>" <%= 'checked=checked' if user.roles.include?(role) %>
                 name="roles[]">
          <label class="form-check-label" for="role-<%= role.id %>">
            <%= role.name %> <small>(<%= role.description %>)</small>
          </label>
        </div>
      <% end %>
      <% else %>
        <div class="input-group input-group-sm">
          <div class="input-group-prepend">
            <div class="input-group-text width-170px">Roles</div>
          </div>
          <input type="text" class="form-control disabled" value="<%= user.role_names.join(', ') %>" disabled>
        </div>
      <% end %>
    </div>
  </div>


  <hr>

  <div class="row">
    <div class="col-md-5">
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <div class="input-group-text width-170px">Password</div>
        </div>
        <%= form.password_field :password, class: 'form-control' %>
      </div>
    </div>
    <div class="col-md-5">
      <small>Leave blank if you do not want to change it.</small>
    </div>
  </div>
  <p></p>

  <div class="row">
    <div class="col-md-5">
      <div class="input-group input-group-sm">
        <div class="input-group-prepend">
          <div class="input-group-text width-170px">Confirm Password</div>
        </div>
        <%= form.password_field :password_confirmation, class: 'form-control' %>
      </div>
    </div>
  </div>
  <p></p>

  <div class="actions">
    <%= form.submit class: 'btn btn-success btn-sm' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header small">
        <h3><em class="fa fa-user-astronaut"></em> Edit '<%= @user.name %>'</h3>
      </div>
      <div class="card-body">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header small">
        <em class="fa fa-user-astronaut"></em> Registered Users
      </div>
      <div class="card-body">

        <table class="table datatable table-striped table-borderless">
          <thead>
          <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Index</th>
            <th>Roles</th>
            <th>Registered</th>
            <th class="no-sort"></th>
          </tr>
          </thead>
          <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= user.name %></td>
              <td><%= user.personal_index %></td>
              <td><%= user.role_names.join(', ') %></td>
              <td><%= user.created_at.to_date %></td>
              <td>
                <%= link_to '<em class="fa fa-edit" title="Edit User"></em>'.html_safe, edit_user_path(user) %>
                <%= link_to '<em class="fa fa-trash-alt" title="Delete User"></em>'.html_safe, user, method: :delete, data: {confirm: 'Are you sure?'} %>
              </td>
            </tr>
          <% end %>
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header small">
        <h3><em class="fa fa-user-astronaut"></em> Create Account</h3>
      </div>
      <div class="card-body">
        <%= render 'form', user: @user %>
      </div>
    </div>
  </div>
</div>